apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: secret-mysql
  namespace: database
spec:
  encryptedData:
    password: AgCMsdB4qRlmmTwVAHWnmSN0uwnfHC+rtSd3bvjSJLl7UMhTuBpTBb0I1A3lYqnvIOETf8/aYOvQJRBZ8AzuIzmLX2pYBu0th3r2uppaQLDq1DUv8JPbWA0mzAhzuUQ5JdH78IsYoUkhOd19aCgkV/1oIBZT1iZh1ClutDKLRGfnisJv73G89wyRCGP/DeWSJrpszzxktLpF1RjAateVYmHsmTFAaqIjk4Jeg2oq1fDfgvi/sz4lD8sf+w87uxBh36KiDE7S59IO79ClRb3NBI8kYwan1bX57DLLhNiCKZ1OomcKswJG8wdCJJnWRKsxtENNJK0mTrVA+PyvmlNMyyg6CbYLl9JY8gzye3r9mprIx8HlP4g5cRF2X2a1Gp60fjXYZShJpfMSRx5wQf2dxsKM88GmjvhksL8AKRd/PSGgJPsA5bQgplQqbdb1EnzwTt3hQ8TPiJtj0WwucsJKRct0Jz7CwBl+DvVAskDFmQD9wnuys6pyABhDtXKlKCBgiqtGW6Rzcar8EKittXW+IMPYxU3RYkQPfhaE7xkcvlML4w64MQOzRZhMWH1cacqBv/QNLhYEkvkOqXjkYxOZQZPCbJ6LtI+XB7z05HHMza7q2qLJoBa22jWBkGYnAjE+ilJAkHeWUXCSS+7ivhyB7zoof9nqlOlO+FL5zjHq1GA/sY7qlawdrWst6Ii1TFNsNOibOB/khPcn+Z0ptAfnolInZqYhEJvwQKfl
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: secret-mysql
      namespace: database

