apiVersion: v1
kind: Secret
metadata:
    name: secret-mysql
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:u8+8ZyS7e5F7F8DeZFICuvplECT3xl1g+w==,iv:LePHfTsUYOV9ycuWwPiCqIVK2e6+abAShZLPzR3/ico=,tag:MpFM7FpAwOON00W9QNh1hQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-29T17:26:19Z"
    mac: ENC[AES256_GCM,data:tf6zlv5ocnLlsjyhChVAztGu9xsUFKjfnddOaYp5o2Xr6dCQirfZQ7d/t/fvCMo/cLn3xRIw1LY/WBl8qPrMsIq6zgGMqoBZpkKRTgVbHBiQSI4hlhNU6g9AZK2by+W0LrFaOtXaE3H/qzE2z2Wa7S/8pf2VuyB8Goz6Cewmr7M=,iv:RUbvhFJdVxJch6IkcTWlxhdNJ8WoaYlx3NmJ60Qn2sc=,tag:IWkIT1/YKdzzQRq/XEPpgw==,type:str]
    pgp:
        - created_at: "2023-12-29T17:26:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQGMA6OKzGeKz9gLAQwAxYfb/wwZ+YR4wC0S5NRz/Mbxt5MP4hz6S08o7wKVIqyP
            lWuklayKKEfEtrf5vj9lUItEdrntZyXPfxSjRsckcM95K4mkxFBIvd2w/CtOPM9o
            myL9No1uqohM/f2g2FS3who2s0vtwLXn1qn8nXau4OYHIRqppwtKjGw4uytGAXK6
            gkamxWQ3mx7+5qENSEifFRiQnfqXN23g+6QYubcL6nj1j0l14M3jXABw6tHqGtU2
            he0aNu89UEqz43X4Hc078CwQS5ns7WfjUXLZvz8azn1VJlE8hNPx4VALoOaXmXTx
            nWXBGhFqpni3U1BPD3i21Ja3Pn0p5EfuvMZa+L1TE7NEAdhAitY+ccuwuSwPjvuE
            Z47yxBB0QJ5ymQ399w6eOPb8QI6iry+i6W4D4tsVdW1gUFsAw4Ru+ApTH0vKxeoF
            h76hl/rE5OeFx2wp9ij9eSXSwGYR7EyLPtSm0T1gKY2mHTFDo14vSq3KXl93784v
            1+YMVg7jyBcj7B/jct+E0lwBz+NeVG4Adsv5Nwzf8w2cVoep/GaOEx2U2fNjLkwY
            8JdcvTRTEMcn0vhV4h4XGAW2MHcyKLX9SNnXjJD3AiVE5GOgyt0SAQrawVkSxk4w
            cv4MjOHhCi7HxJeTmQ==
            =Dke4
            -----END PGP MESSAGE-----
          fp: 2FA565120F39F51F
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
